const router = require('express').Router();
const prisma = require('../config/prisma');
const { authenticate, authorize } = require('../middleware/auth');
router.use(authenticate);
router.post('/purchases', authorize('ADMIN'), async(req,res,next)=>{try{
  const b=req.body, items=b.items||[]; if(!b.invoiceNo||!items.length) return res.status(400).json({message:'Invoice number and items are required'});
  const result=await prisma.$transaction(async(tx)=>{let subtotal=0,total=0,gstTotal=0; const rows=[];
    for(const i of items){const p=await tx.product.findUnique({where:{id:Number(i.productId)}}); if(!p) throw new Error('Product not found'); const q=Number(i.quantity); const price=Number(i.unitPurchasePrice??p.purchasePrice); const discount=Number(i.discount||0); const taxable=Math.max(0,q*price-discount); const gst=taxable*Number(i.gstPercentage||0)/100; subtotal+=q*price;gstTotal+=gst;total+=taxable+gst;rows.push({productId:p.id,quantity:q,unitPurchasePrice:price,discount,gstPercentage:Number(i.gstPercentage||0),total:taxable+gst});}
    const purchase=await tx.purchase.create({data:{invoiceNo:b.invoiceNo,supplierId:b.supplierId?Number(b.supplierId):null,purchaseDate:b.purchaseDate?new Date(b.purchaseDate):new Date(),subtotal,discount:Number(b.discount||0),gstTotal,total,paymentStatus:b.paymentStatus||'PENDING',notes:b.notes||null,items:{create:rows}}});
    for(const row of rows){await tx.product.update({where:{id:row.productId},data:{currentStock:{increment:row.quantity}}});await tx.stockTransaction.create({data:{productId:row.productId,userId:req.user.id,type:'PURCHASE_IN',quantity:row.quantity,reference:String(purchase.id),notes:'Purchase '+b.invoiceNo}})}
    return purchase;
  }); res.status(201).json(result);
}catch(e){next(e)}});
router.post('/stock/out', authorize('ADMIN'), async(req,res,next)=>{try{const b=req.body,q=Number(b.quantity);if(!b.productId||q<=0)return res.status(400).json({message:'Valid product and quantity are required'});const result=await prisma.$transaction(async(tx)=>{const p=await tx.product.findUnique({where:{id:Number(b.productId)}});if(!p)throw new Error('Product not found');if(Number(p.currentStock)<q)throw new Error('Insufficient stock');const updated=await tx.product.update({where:{id:p.id},data:{currentStock:{decrement:q}}});await tx.stockTransaction.create({data:{productId:p.id,userId:req.user.id,type:'STOCK_OUT',quantity:-q,reference:b.reason||'ADJUSTMENT',notes:b.notes||null}});return updated});res.json(result)}catch(e){next(e)}});
router.post('/sales', async(req,res,next)=>{try{const b=req.body,items=b.items||[];if(!items.length)return res.status(400).json({message:'Cart is empty'});const result=await prisma.$transaction(async(tx)=>{const setting=await tx.shopSetting.findUnique({where:{id:1}});const invoiceNo=(setting?.invoicePrefix||'INV')+'-'+Date.now();let subtotal=0,discount=Number(b.discount||0),gstTotal=0;const rows=[];
  for(const i of items){const p=await tx.product.findUnique({where:{id:Number(i.productId)}});if(!p)throw new Error('Product not found');const q=Number(i.quantity);if(q<=0)throw new Error('Quantity must be positive');if(!setting?.allowNegativeStock&&Number(p.currentStock)<q)throw new Error('Insufficient stock for '+p.name);const price=Number(p.sellingPrice);const lineDiscount=Number(i.discount||0);const taxable=Math.max(0,q*price-lineDiscount);const gst=p.gstApplicable?taxable*Number(p.gstPercentage)/100:0;subtotal+=q*price;gstTotal+=gst;rows.push({productId:p.id,quantity:q,unitPrice:price,discount:lineDiscount,taxableValue:taxable,gstPercentage:p.gstApplicable?Number(p.gstPercentage):0,gstAmount:gst});}
  const taxableAfterBill=Math.max(0,subtotal-discount); const scale=subtotal?taxableAfterBill/subtotal:1; const adjusted=rows.map(r=>({...r,taxableValue:Number((r.taxableValue*scale).toFixed(2)),gstAmount:Number((r.gstAmount*scale).toFixed(2))}));gstTotal=adjusted.reduce((s,r)=>s+r.gstAmount,0);const grandTotal=Number((taxableAfterBill+gstTotal).toFixed(2));const sale=await tx.sale.create({data:{invoiceNo,customerId:b.customerId?Number(b.customerId):null,userId:req.user.id,subtotal,discount,gstTotal,grandTotal,paymentMethod:b.paymentMethod||'CASH',amountPaid:Number(b.amountPaid??grandTotal),items:{create:adjusted}}});
  for(const r of adjusted){await tx.product.update({where:{id:r.productId},data:{currentStock:{decrement:r.quantity}}});await tx.stockTransaction.create({data:{productId:r.productId,userId:req.user.id,type:'SALE_OUT',quantity:-r.quantity,reference:String(sale.id),notes:'Sale '+invoiceNo}})}await tx.payment.create({data:{saleId:sale.id,customerId:b.customerId?Number(b.customerId):null,amount:Number(b.amountPaid??grandTotal),method:b.paymentMethod||'CASH'}});if(b.customerId&&b.paymentMethod==='CREDIT')await tx.customer.update({where:{id:Number(b.customerId)},data:{currentBalance:{increment:grandTotal}}});return tx.sale.findUnique({where:{id:sale.id},include:{items:{include:{product:true}},customer:true,payment:true}});});res.status(201).json(result)}catch(e){next(e)}});
router.get('/sales', async(req,res,next)=>{try{res.json(await prisma.sale.findMany({include:{customer:true,user:{select:{name:true}},items:{include:{product:true}}},orderBy:{createdAt:'desc'},take:100}))}catch(e){next(e)}});
router.get('/purchases', authorize('ADMIN'), async(req,res,next)=>{try{res.json(await prisma.purchase.findMany({include:{supplier:true,items:{include:{product:true}}},orderBy:{createdAt:'desc'},take:100}))}catch(e){next(e)}});
router.get('/inventory', async(req,res,next)=>{try{res.json(await prisma.product.findMany({where:{active:true},include:{category:true},orderBy:{name:'asc'}}))}catch(e){next(e)}});
router.get('/inventory/transactions', authorize('ADMIN'), async(req,res,next)=>{try{res.json(await prisma.stockTransaction.findMany({include:{product:true,user:{select:{name:true}}},orderBy:{createdAt:'desc'},take:200}))}catch(e){next(e)}});
router.post('/expenses', authorize('ADMIN'), async(req,res,next)=>{try{const b=req.body;if(!b.category||Number(b.amount)<=0)return res.status(400).json({message:'Category and a positive amount are required'});res.status(201).json(await prisma.expense.create({data:{expenseDate:b.expenseDate?new Date(b.expenseDate):new Date(),category:b.category,description:b.description||null,amount:Number(b.amount),paymentMethod:b.paymentMethod||'CASH',notes:b.notes||null}}))}catch(e){next(e)}});
router.get('/expenses', authorize('ADMIN'), async(req,res,next)=>{try{res.json(await prisma.expense.findMany({orderBy:{expenseDate:'desc'},take:100}))}catch(e){next(e)}});
module.exports=router;
